{% set name = "apache-airflow-providers-segment" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-segment-{{ version }}.tar.gz
  sha256: c9de8018dbe47ea9b8038201e5e4c5182b987fa3e9a49d9e6adb78e64f331efa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=67.2.0,<68.0.0
    - pip
  run:
    - python >=3.8
    - analytics-python >=1.2.9
    - apache-airflow >=2.4.0

test:
  imports:
    - airflow.providers.segment
    - airflow.providers.segment.hooks
  commands:
    # failing because package was renamed segemnt-analytics-python
    # - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-segment package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-segment/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
