{% set name = "apache-airflow-providers-segment" %}
{% set version = "2.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-segment-{{ version }}.tar.gz
  sha256: 0bf7ec589fa6c2a4d4a2c5608a99b87323688cc67dbd8c37c205c96d7f7b47b6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - apache-airflow >=2.1.0
    - analytics-python >=1.2.9

test:
  imports:
    - airflow.providers.segment
    - airflow.providers.segment.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Segment for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-segment/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
